    try
    {
    }
    Catch(Exception e)
    {
     Switch(e.ExceptionType)
     {
         case ExceptionType.Val1:
           // Handle accordingly  
           break;
     }
    }
 
