    try{
      line 1;
    }
    catch(Exception exc){
      //Error handling logic here
    }
    finally{
      line 2;
      line 3;
      .
      .
      .
      line n;
    }
